# Generated by Django 3.2.18 on 2023-04-19 12:18

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('add_recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='instructions',
            field=djrichtextfield.models.RichTextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=djrichtextfield.models.RichTextField(max_length=10000),
        ),
    ]
