# Generated by Django 3.2.18 on 2023-06-08 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('add_recipe', '0003_recipes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='recipe_dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
