# Generated by Django 3.2.18 on 2023-06-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_recipe', '0004_recipes_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='dislikes',
        ),
    ]
